name: "generate-version-and-release-notes"
description: "generates semver and changelog.md after a pull request has been merge"
runs:
  using: "composite"
  steps:
    - run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        node ${{ github.action_path }}/../generate-version-and-release-notes.js
      shell: bash
